spring.application.name=Person

# Clean console log
spring.main.banner-mode=CONSOLE
logging.level.root=warn

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/person_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.open-in-view=false

# Add logging to SQL statements
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# Configure JPA to auto create tables
# update: The update config will keep data in table and will update and alter the tables
# spring.jpa.hibernate.ddl-auto=update

# Swagger custom endpoint
# springdoc.swagger-ui.path=/docs

